version: "3.8"

services:
  react-query-builder-demo:
    container_name: react-query-builder-demo
    image: app-prod
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "8080:80"
