version: "3.8"

services:
  react-query-builder-demo:
    container_name:  react-query-builder-demo-prod
    image: app-prod
    build:
      context: .
      target: production
    ports:
      - "8080:80"
      